services:
  app:
    build:
      context: .
    command: npm run dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules # Avoid overwriting node_modules of main bind (.:/app)