services:
  app:
    build:
      context: .
    command: npm run start
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./db:/app/db
